package entities;
// Generated Apr 19, 2017 1:59:16 PM by Hibernate Tools 4.3.1



/**
 * Uploads generated by hbm2java
 */
public class Uploads{


     private int uploadId;
     private String title;
     private String userid;
     private String userName;
     private String dt;
     private String tm;
     private Integer lifetm;
     private String lifespan;
     private String intro;
     private String path;
     private String seckey;
     private String filesize;
     private String ext;
     private String status;
     private String clientId;
     private String branch;
     private String hashval;
     private float encryptionTm;
     private float decryptionTm;

    public Uploads() {
    }

	
    public Uploads(int uploadId, String filesize, String ext, String status, float encryptionTm, float decryptionTm) {
        this.uploadId = uploadId;
        this.filesize = filesize;
        this.ext = ext;
        this.status = status;
        this.encryptionTm = encryptionTm;
        this.decryptionTm = decryptionTm;
    }
    public Uploads(int uploadId, String title, String userid, String userName, String dt, String tm, Integer lifetm, String lifespan, String intro, String path, String seckey, String filesize, String ext, String status, String clientId, String branch, String hashval, float encryptionTm, float decryptionTm) {
       this.uploadId = uploadId;
       this.title = title;
       this.userid = userid;
       this.userName = userName;
       this.dt = dt;
       this.tm = tm;
       this.lifetm = lifetm;
       this.lifespan = lifespan;
       this.intro = intro;
       this.path = path;
       this.seckey = seckey;
       this.filesize = filesize;
       this.ext = ext;
       this.status = status;
       this.clientId = clientId;
       this.branch = branch;
       this.hashval = hashval;
       this.encryptionTm = encryptionTm;
       this.decryptionTm = decryptionTm;
    }
   
    public int getUploadId() {
        return this.uploadId;
    }
    
    public void setUploadId(int uploadId) {
        this.uploadId = uploadId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getDt() {
        return this.dt;
    }
    
    public void setDt(String dt) {
        this.dt = dt;
    }
    public String getTm() {
        return this.tm;
    }
    
    public void setTm(String tm) {
        this.tm = tm;
    }
    public Integer getLifetm() {
        return this.lifetm;
    }
    
    public void setLifetm(Integer lifetm) {
        this.lifetm = lifetm;
    }
    public String getLifespan() {
        return this.lifespan;
    }
    
    public void setLifespan(String lifespan) {
        this.lifespan = lifespan;
    }
    public String getIntro() {
        return this.intro;
    }
    
    public void setIntro(String intro) {
        this.intro = intro;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public String getSeckey() {
        return this.seckey;
    }
    
    public void setSeckey(String seckey) {
        this.seckey = seckey;
    }
    public String getFilesize() {
        return this.filesize;
    }
    
    public void setFilesize(String filesize) {
        this.filesize = filesize;
    }
    public String getExt() {
        return this.ext;
    }
    
    public void setExt(String ext) {
        this.ext = ext;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getClientId() {
        return this.clientId;
    }
    
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }
    public String getHashval() {
        return this.hashval;
    }
    
    public void setHashval(String hashval) {
        this.hashval = hashval;
    }
    public float getEncryptionTm() {
        return this.encryptionTm;
    }
    
    public void setEncryptionTm(float encryptionTm) {
        this.encryptionTm = encryptionTm;
    }
    public float getDecryptionTm() {
        return this.decryptionTm;
    }
    
    public void setDecryptionTm(float decryptionTm) {
        this.decryptionTm = decryptionTm;
    }




}


